version: "3.9"

services:

  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westus.livediagnostics.monitor.azure.com/
      - APPINSIGHTS_INSTRUMENTATIONKEY=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c
    networks:
      - petstorebridge

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westus.livediagnostics.monitor.azure.com/
    networks:
      - petstorebridge

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westus.livediagnostics.monitor.azure.com/
      - APPINSIGHTS_INSTRUMENTATIONKEY=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c
    networks:
      - petstorebridge

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c;IngestionEndpoint=https://westus-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westus.livediagnostics.monitor.azure.com/
      - APPINSIGHTS_INSTRUMENTATIONKEY=1c3d4ca5-a1ec-4986-83a2-25e38986ac2c
    networks:
      - petstorebridge

networks:
  petstorebridge:
    driver: bridge
